server:
  port: 80

github:
  client:
    id: "f73b32b1520dcd65f875"
    secret: "299267086283a03d8a0c7eff058d113ddcb9570e"
  redirect:
    url: "http://localhost/callback"


#连接池
spring:
  datasource:
    url: jdbc:mysql://longlongaixuexi.mysql.rds.aliyuncs.com:3306/my_blog?characterEncoding=utf8&useSSL=true
    username: star_long
    password: balong255664!
    driver-class-name: com.mysql.jdbc.Driver

# 驼峰命名
mybatis:
  type-aliases-package: blog.mingmomcoco.myblog.model
  type-handlers-package: blog.mingmomcoco.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
